version: "3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgresUser
            POSTGRES_PASSWORD: postgresPW
            POSTGRES_DB: postgresDB
        ports:
            - "5455:5432"
        volumes:
            - ./db:/var/lib/postgresql/data
    server:
        image: fmibackend:latest
        ports:
            - "3000:3000"
        depends_on:
            - db
    web:
        image: fmifrontend:latest
        ports:
            - "80:3000"
        depends_on:
            - server
